server:
  port: 8080

spring:
  datasource:
    url: "jdbc:postgresql://localhost:5332/school_management"
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  main:
    web-application-type: servlet
